apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  log
  template:
    metadata:
      labels:
        app:  log
    spec:
      containers:
        - name: log-generator
          image: younes0204/log-generator
          env:
            - name: PORT
              value: '8081'
          ports:
            - containerPort: 8081
        - name: log-reader
          image: younes0204/log-reader
          env:
            - name: PORT
              value: '8082'
          ports:
            - containerPort: 8082
