apiVersion: v1
kind: Service
metadata:
  name: crudapp-svc
spec:
  type: ClusterIP
  selector:
    app:  crudapp
  ports:
    - name: crudapp-service
      protocol: TCP
      port: 4444
      targetPort: 3000