apiVersion: apps/v1
kind: Deployment
metadata:
  name: strgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strgenerator
  template:
    metadata:
      labels:
        app: strgenerator
    spec:
      containers:
        - name: strgenerator
          image: younes0204/random_string_generator