apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strgenerator-ing
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strgenerator-svc
                port:
                  number: 4444 